In [74]:
import pandas as pd
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt
from tqdm import tqdm

import torch, torchvision
print(torch.__version__, torch.cuda.is_available())

# Check MMDetection installation
import mmdet
print(mmdet.__version__)

# Check mmcv installation
from mmcv.ops import get_compiling_cuda_version, get_compiler_version
print(get_compiling_cuda_version())
print(get_compiler_version())

seed = 1015
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)

os.environ["CUDA_VISIBLE_DEVICES"]="0"
PATH = "../../cpt_data/ct_new/"
from pycocotools.coco import COCO
from pycocotools.mask import encode,decode,area,toBbox
import json

1.7.1 True
2.8.0
10.0
GCC 7.5

In [100]:
dir_path = "../data/random_shift/img/"
target = pd.read_csv('../data/random_shift/random_shift_target.csv')
target["height"] = 512
target["width"] = target.end_x - target.start_x
target["img_path"] = target["person_mul_index"] + '.png'
target
coco_bbox = pd.DataFrame(target.img_path)
coco_bbox['left'] = target.loc[:, 'start_x'].values
coco_bbox['top'] = [0 for i in range(len(target))]
coco_bbox['width'] = target.loc[:, 'width'].values
coco_bbox['height'] = target.loc[:, 'height'].values                             
coco_bbox.index = coco_bbox.index + 1
coco_bbox

             img_path  left  top  width  height
1    00003552_252.png   171    0     86     512
2    00003552_253.png   397    0     86     512
3    00003552_254.png   184    0     86     512
4    00003552_255.png   284    0     86     512
5    00003552_256.png   188    0     86     512
..                ...   ...  ...    ...     ...
536  00004237_256.png   295    0     80     512
537  00004237_257.png   275    0     80     512
538  00004237_258.png   329    0     80     512
539  00004237_259.png   195    0     80     512
540  00004237_260.png   185    0     80     512

[540 rows x 5 columns]

In [109]:
def gen_objs(df):
    img_lists = df.index
    imgs = list()
    objs = list()   
    
    ## gen images information
    for idx, img_path in tqdm(enumerate(img_lists)):
        single_img_obj = {}
        single_img_obj['file_name'] = df.loc[img_path, "img_path"]
        single_img_obj['height'] = 512
        single_img_obj['width'] = 512                     
        single_img_obj['id'] = idx + 1       
        imgs.append(single_img_obj)
        
  
    ## gen objs information    
    for idx, img_path in tqdm(enumerate(img_lists)):
        single_obj = {}
        single_obj['id'] = idx + 1
        single_obj['image_id'] = img_path
        single_obj['category_id'] = 1#int(df['impact'][j] ) ## You need to customize if you want to add some 'impact' class
        single_obj['area'] = float(df.loc[img_path, 'width'] * df.loc[img_path, 'height'])
        single_obj['bbox'] = [int(df.loc[img_path, 'left']),
                              int(df.loc[img_path, 'top']),
                              int(df.loc[img_path, 'width']),
                              int(df.loc[img_path, 'height'])]
        single_obj['iscrowd'] = 0        
        objs.append(single_obj)
    print(f'images: {len(imgs)}, objs: {len(objs)}')
    return imgs, objs

def gen_classes(CLASSES):
    classes = list()      
    for i, CLASS in enumerate(CLASSES):
        single_class = {} 
        single_class['id'] = i + 1
        single_class['name'] = CLASS
        classes.append(single_class)
    return classes

def gen_coco(outpath, classes, objs, imgs, train=True):
    if train:
        data_dict = {}
        data_dict['images'] = []
        data_dict['annotations'] = []
        data_dict['categories'] = []
        data_dict['images'].extend(imgs)
        data_dict['annotations'].extend(objs)
        data_dict['categories'].extend(classes)
        
    else:
        data_dict = {}
        data_dict['images'] = []
        data_dict['categories'] = []
        
        data_dict['images'].extend(imgs)
        data_dict['categories'].extend(classes)   

    with open(outpath, 'w') as f_out:
        json.dump(data_dict, f_out)

In [110]:
CLASSES = ['stomach']
classes = gen_classes(CLASSES)
classes

[{'id': 1, 'name': 'stomach'}]

In [111]:
len(coco_bbox)

540

In [112]:
train_df = coco_bbox.loc[:400,:]
valid_df = coco_bbox.loc[400:,:]

In [113]:
valid_df

             img_path  left  top  width  height
400  00004240_255.png   204    0     77     512
401  00004240_256.png   104    0     77     512
402  00004240_257.png   163    0     77     512
403  00004240_258.png   150    0     77     512
404  00004240_259.png   271    0     77     512
..                ...   ...  ...    ...     ...
536  00004237_256.png   295    0     80     512
537  00004237_257.png   275    0     80     512
538  00004237_258.png   329    0     80     512
539  00004237_259.png   195    0     80     512
540  00004237_260.png   185    0     80     512

[141 rows x 5 columns]

In [114]:
train_imgs, train_objs = gen_objs(train_df)
valid_imgs, valid_objs = gen_objs(valid_df)

400it [00:00, 95141.30it/s]
400it [00:00, 19449.59it/s]
141it [00:00, 85709.69it/s]
141it [00:00, 17058.38it/s]

images: 400, objs: 400
images: 141, objs: 141

In [115]:
gen_coco('coco_json/train.json', classes, train_objs, train_imgs, train=True)
gen_coco('coco_json/valid.json', classes, valid_objs, valid_imgs, train=True)